name: Feature request
description: Propose a new D-SafeLogger feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature description
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use case
    validations:
      required: true
  - type: textarea
    id: workaround
    attributes:
      label: Current workaround
    validations:
      required: false
