"""D-SafeLogger CLI utility (dsafelogger command)."""

from __future__ import annotations

import argparse
import sys
import time
from datetime import datetime
from pathlib import Path

INI_TEMPLATE = """\
; =============================================================================
; D-SafeLogger configuration template
; Generated by: dsafelogger init
;
; Lines starting with ';' are comments.
; Uncomment and modify values as needed.
; =============================================================================

[global]

; --- Basic ---
; default_level = INFO
; log_path = .
; pg_name = Default
; env_prefix = D_LOG
; console_out = true
; is_async = false

; --- Log format (choose ONE) ---
;
;   Option A: Human-readable (default)
;
; fmt = %(asctime)s.%(msecs)03d [%(levelname)-3s][%(filename)s:%(lineno)s:%(funcName)s] %(message)s
; datefmt = %Y-%m-%d %H:%M:%S
;
;   Option B: Structured JSON Lines
;
; structured = false

; --- Routing mode (choose ONE) ---
;
;   'none'              : Single file, no switching (default)
;   'daily'             : Switch at midnight
;   'hourly'            : Switch every hour
;   'min_interval'      : Switch at fixed-minute boundaries
;   'startup_interval'  : Switch after elapsed time from startup
;   'size'              : Switch when file exceeds max_bytes
;   'count'             : Switch when file exceeds max_lines
;   'cyclic_weekday'    : Overwrite by day-of-week (7 files)
;   'cyclic_month'      : Overwrite by month (12 files)
;
; routing_mode = none

;   Parameters for 'min_interval':
;     interval must be a divisor of 60 (5, 10, 15, 20, 30, etc.)
; interval = 10

;   Parameters for 'startup_interval':
;     integer (minutes) or duration string ('12h', '1d')
; interval = 10

;   Parameters for 'size':
; max_bytes = 0

;   Parameters for 'count':
; max_lines = 0

;   Parameters for 'size' / 'count' (cyclic mode):
;     Omit or leave empty for overflow-error mode (keep all files).
; max_count =
; suffix_digits = 3

; --- Retention (requires routing_mode != 'none') ---
;
;   backup_count: Number of old files to keep. 0 = no deletion.
;   archive_mode: If true, old files are ZIP-archived instead of deleted.
;
; backup_count = 0
; archive_mode = false

; --- Integrity verification (requires routing_mode != 'none') ---
;
;   enable_hash:   Generate .sha256 sidecar on file switch.
;   manifest_path: Append hash history to this file.
;
; enable_hash = false
; manifest_path =

; --- Console color palette ---
;
;   Customize ANSI color codes for each log level.
;   Values are SGR parameter numbers.
;
; color_dbg = 36
; color_inf = 32
; color_war = 33
; color_err = 31
; color_cri = 1;31

; --- Sensitive keyword customisation ---
;
; sens_kws =
; sens_kws_replace = false

; =============================================================================
; Per-module settings
;
; Section name format: [dsafelogger:<module_name>]
; 'level' is required. Other keys are optional.
; =============================================================================

; [dsafelogger:myapp.db]
; level = DEBUG

; [dsafelogger:myapp.api]
; level = ERROR
; path = /var/log/myapp/api.log
; routing_mode = size
; max_bytes = 10485760
; max_count = 5
; suffix_digits = 2
; backup_count = 10
"""


def cmd_init() -> None:
    """Print INI config template to stdout."""
    print(INI_TEMPLATE, end='')


def cmd_ls(log_dir: str) -> None:
    """List D-SafeLogger log files grouped by pg_name."""
    log_path = Path(log_dir)
    if not log_path.is_dir():
        print(f'Error: "{log_dir}" is not a directory.', file=sys.stderr)
        sys.exit(1)

    files = sorted(log_path.glob('*.log'), key=lambda p: p.stat().st_mtime, reverse=True)
    if not files:
        print('No log files found.')
        return

    # Group by pg_name (extract prefix before last underscore or use full stem)
    groups: dict[str, list[Path]] = {}
    for f in files:
        name = f.stem
        # Try to extract pg_name (everything before the last routing suffix)
        parts = name.rsplit('_', 1)
        if len(parts) == 2:
            pg_name = parts[0]
        else:
            pg_name = name
        groups.setdefault(pg_name, []).append(f)

    for pg_name, file_list in sorted(groups.items()):
        latest = file_list[0]
        stat = latest.stat()
        mtime = datetime.fromtimestamp(stat.st_mtime)
        print(
            f'{pg_name:20s}  {latest.name:40s}  '
            f'{stat.st_size:>10,} bytes  '
            f'{mtime:%Y-%m-%d %H:%M:%S}'
        )


def cmd_tail(
    log_dir: str,
    pg_name: str,
    initial_lines: int,
    poll_interval: float,
) -> None:
    """Follow latest log file for a given pg_name, with transparent file switching."""
    log_path = Path(log_dir)
    current_file: Path | None = None
    file_handle = None
    position: int = 0

    try:
        while True:
            # Find latest file matching pg_name
            candidates = sorted(
                log_path.glob(f'{pg_name}_*.log'),
                key=lambda p: p.stat().st_mtime,
                reverse=True,
            )
            if not candidates:
                single = log_path / f'{pg_name}.log'
                if single.exists():
                    candidates = [single]

            if not candidates:
                time.sleep(poll_interval)
                continue

            latest = candidates[0]

            # File switch detection
            if latest != current_file:
                # Read remaining from old file first
                if file_handle:
                    file_handle.seek(position)
                    remaining = file_handle.readlines()
                    for line in remaining:
                        print(line, end='')
                    file_handle.close()

                current_file = latest
                file_handle = open(current_file, 'r', encoding='utf-8')
                lines = file_handle.readlines()
                for line in lines[-initial_lines:]:
                    print(line, end='')
                position = file_handle.tell()
            else:
                assert file_handle is not None
                file_handle.seek(position)
                new_lines = file_handle.readlines()
                for line in new_lines:
                    print(line, end='')
                position = file_handle.tell()

            time.sleep(poll_interval)
    except KeyboardInterrupt:
        pass
    finally:
        if file_handle:
            file_handle.close()


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog='dsafelogger',
        description='D-SafeLogger CLI utility',
    )
    subparsers = parser.add_subparsers(dest='command', required=True)

    # init
    subparsers.add_parser('init', help='Print INI config template to stdout')

    # ls
    ls_parser = subparsers.add_parser('ls', help='List log files')
    ls_parser.add_argument(
        'log_dir', nargs='?', default='.',
        help='Log directory path (default: current)',
    )

    # tail
    tail_parser = subparsers.add_parser('tail', help='Follow log file in real-time')
    tail_parser.add_argument(
        '-f', '--follow', action='store_true', required=True,
        help='Follow file',
    )
    tail_parser.add_argument('log_dir', help='Log directory path')
    tail_parser.add_argument('pg_name', help='Program name to follow')
    tail_parser.add_argument(
        '-n', '--lines', type=int, default=10,
        help='Initial lines to display (default: 10)',
    )
    tail_parser.add_argument(
        '--poll-interval', type=float, default=0.5,
        help='Polling interval in seconds (default: 0.5)',
    )

    args = parser.parse_args()

    if args.command == 'init':
        cmd_init()
    elif args.command == 'ls':
        cmd_ls(args.log_dir)
    elif args.command == 'tail':
        cmd_tail(args.log_dir, args.pg_name, args.lines, args.poll_interval)
